courses.2ndskiesforex.com/protected/modules/admin/controllers/CommentController.php
<?php

class CommentController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			/*array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),*/
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','create','update','index','view'),
				'users'=>UserModule::getAdmins(),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
        $model = $this->loadModel($id);
        $this->redirect($model->getCommentUrl($id));
        /*$this->render('view',array(
			'model'=>$this->loadModel($id),
		));*/
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Comment;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Comment']))
		{
			$model->attributes=$_POST['Comment'];
            $model->date_created = $model->date_changed = new CDbExpression('NOW()');
            $model->user_id = Yii::app()->user->id;

            $comment = Comment::model()->findByAttributes(array('topic_id'=>$model->topic_id));

            if(empty($comment)) $model->is_first = 1;

            if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Comment']))
		{
			$model->attributes=$_POST['Comment'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Comment');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Comment('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Comment']))
			$model->attributes=$_GET['Comment'];

		$this->render('/comment/admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Comment::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

    public function getPage($model,$topicId)
    {
        $pages = $model->countByAttributes(array('topic_id'=>$topicId));
        $page = $pages/10;
        if($pages%10 == 0) return ++$page;
        return ceil($page);
    }
}

courses.2ndskiesforex.com/protected/modules/admin/controllers/TopicController.php
<?php

class TopicController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
		/*array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),*/
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index','view','create','update','admin','delete','releaseAndDiscussion'),
				'users'=>UserModule::getAdmins(),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Topic;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Topic']))
		{
			$model->attributes=$_POST['Topic'];
            $model->date_created = $model->date_changed = new CDbExpression('NOW()');
            $model->user_id = Yii::app()->user->id;

			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Topic']))
		{
			$model->attributes=$_POST['Topic'];//die(var_dump($model->attributes));
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	public function actionReleaseAndDiscussion()
	{
		if (Yii::app()->request->isAjaxRequest) {
			$topics = Yii::app()->request->getParam('Topic', false);
			if ($topics)
				foreach ($topics as $key => $topic)
					Topic::model()->updateByPk($key, $topic);
		}
		Yii::app()->end();
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Topic');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Topic('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Topic']))
			$model->attributes=$_GET['Topic'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Topic::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='topic-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

courses.2ndskiesforex.com/protected/modules/admin/views/comment/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'comment-form',
	'enableAjaxValidation'=>false,
	'type'=>'horizontal',
	'htmlOptions'=>array('class'=>'wysiwyg-form'),
)); ?>

	<p class="hint">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->textFieldRow($model,'topic_id',array('class'=>'span5')); ?>

    <?php echo $form->errorSummary($model); ?>
	<div class="control-group">
	    <?php $this->widget('ext.redactorWidget.ImperaviRedactorWidget',array(
	        'model'=>$model,
	        'attribute'=>'text',
	        'name'=>'redactor',
            'options'=>array(
                'minHeight'=>200,
                'convertVideoLinks'=> true,
                'convertImageLinks'=> true,
                'fileUpload'=>Yii::app()->createUrl('topic/upload'),
                'convertLinks'=>true,
                'dragUpload'=>true,
                'fileUploadErrorCallback'=>new CJavaScriptExpression(
                    'function(obj,json) { alert(json.error); }'
                ),
                'imageUpload'=>Yii::app()->createUrl('topic/upload'),
                'imageUploadErrorCallback'=>new CJavaScriptExpression(
                    'function(obj,json) { alert(json.error); }'
                ),
            ),
	    ));
	    ?>
	</div>


	<div class="clearfix">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'inverse',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
			'htmlOptions'=>array('class'=>'pull-right')
		)); ?>
	</div>

<?php $this->endWidget(); ?>

courses.2ndskiesforex.com/protected/modules/admin/views/comment/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'type'=>'horizontal',
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id'); ?>

	<?php echo $form->textFieldRow($model,'topic_id'); ?>

	<?php echo $form->textFieldRow($model,'user_id'); ?>

	<?php echo $form->textAreaRow($model,'text',array('rows'=>6, 'cols'=>50)); ?>

	<?php echo $form->textFieldRow($model,'date_created'); ?>

	<?php echo $form->textFieldRow($model,'date_changed'); ?>

    <?php echo $form->textFieldRow($model,'is_first'); ?>

	<div class="controls">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

courses.2ndskiesforex.com/protected/modules/admin/views/comment/_search_item.php
<?php
// for global searching
if (is_array($data)) {
    $obj = new Comment();
    $obj->id = $data['id'];
    $obj->attributes = $data;
    $data = $obj;
}
?>
<div class="alert alert-block alert-info" xmlns="//www.w3.org/1999/html">
    <div class="media">
        <h4><?=CHtml::link($data->topic->subject, Yii::app()->createUrl('topic/view',array('id'=>$data->topic->id)))?></h4>
        <div class="span9">
            <div>
                <small><span >Posted by <b><a href="#"><?=$data->user->username ?></a></b><i class="muted"> >> </i><?php if(isset($data->date_created)) echo $data->getDate($data->date_created) ?></span></small>
            </div>
            <p><?=$data->text ?></p>
        </div>
        <div class="media-body">
            <img class="img-rounded" alt="" src="<?=$data->userImage ?>">
            <p>
                <b><?=$data->user->username ?></b><br>
                <br><small>Posts: <i class="muted"><?=$data->posts ?></i></small><br>
                <small>Joined: <i class="muted"><?=$data->user->create_at ?></i></small>
            </p>

        </div>
    </div>
</div>

courses.2ndskiesforex.com/protected/modules/admin/views/comment/_view.php
<div class="well well-small">
	<ul class="unstyled">
		<li>
			<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
			<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
		</li>
		<li>
			<b><?php echo CHtml::encode($data->getAttributeLabel('topic_id')); ?>:</b>
			<?php echo CHtml::encode($data->topic_id); ?>
		</li>
		<li>
			<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
			<?php echo CHtml::encode($data->user_id); ?>
		</li>
		<li>
			<b><?php echo CHtml::encode($data->getAttributeLabel('date_created')); ?>:</b>
			<?php echo CHtml::encode($data->date_created); ?>
		</li>
		<li>
			<b><?php echo CHtml::encode($data->getAttributeLabel('date_changed')); ?>:</b>
			<?php echo CHtml::encode($data->date_changed); ?>
		</li>
        <li>
            <b><?php echo CHtml::encode($data->getAttributeLabel('is_first')); ?>:</b>
            <?php echo CHtml::encode($data->is_first); ?>
        </li>
		<li>
			<b><?php echo CHtml::encode($data->getAttributeLabel('text')); ?>:</b>
			<?php echo CHtml::encode($data->text); ?>
		</li>
	</ul>
</div>

courses.2ndskiesforex.com/protected/modules/admin/views/comment/admin.php
<?php
$this->breadcrumbs=array(
	'Comments'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Comment','url'=>array('index')),
	array('label'=>'Create Comment','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggleClass('hidden');
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('topic-grid', {
		data: $(this).serialize()
	});
});
");
?>

<h1 class="content-title"><?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn-success btn-small btn pull-right', 'data-toggle'=>'button')); ?>Manage Comments</h1>

<p>You may optionally enter a comparison operator <code><b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b></code> at the beginning of each of your search values to specify how the comparison should be done.</p>

<div class="search-form hidden">
	<?php $this->renderPartial('_search',array(
		'model'=>$model,
	)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'comment-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'topic_id',
		'user_id',
		'text',
		'date_created',
		'date_changed',
        'is_first',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

courses.2ndskiesforex.com/protected/modules/admin/views/comment/create.php
<?php
$this->breadcrumbs=array(
	'Topic'=>array('topic/list'),
	'Create',
);

?>

<h1 class="content-title">Create Comment</h1>

<?php echo $this->renderPartial('/comment/_form', array('model'=>$model)); ?>

courses.2ndskiesforex.com/protected/modules/admin/views/comment/index.php
<?php
$this->breadcrumbs=array(
	'Comments',
);

$this->menu=array(
	array('label'=>'Create Comment','url'=>array('create')),
	array('label'=>'Manage Comment','url'=>array('admin')),
);
?>

<h1 class="content-title">Comments</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

courses.2ndskiesforex.com/protected/modules/admin/views/comment/update.php
<?php
$this->breadcrumbs=array(
	'Comments'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Comment','url'=>array('index')),
	array('label'=>'Create Comment','url'=>array('create')),
	array('label'=>'View Comment','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Comment','url'=>array('admin')),
);
?>

<h1>Update Comment <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

courses.2ndskiesforex.com/protected/modules/admin/views/comment/view.php
<?php
$this->breadcrumbs=array(
	'Comments'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Comment','url'=>array('index')),
	array('label'=>'Create Comment','url'=>array('create')),
	array('label'=>'Update Comment','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete Comment','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Comment','url'=>array('admin')),
);
?>

<h1 class="content-title">View Comment #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'topic_id',
		'user_id',
		'text',
		'date_created',
		'date_changed',
        'is_first'
	),
)); ?>