courses.2ndskiesforex.com/protected/modules/user/models/User.php
<?php

/**
 * The followings are the available columns in table 'users':
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $activkey
 * @property integer $createtime
 * @property integer $lastvisit
 * @property integer $role
 * @property integer $status
 * @property timestamp $create_at
 * @property timestamp $lastvisit_at
 * @property string $uniqid
 * @property integer $ontraportId
 * @property MakeUniqueBehavior $makeUniqueBehavior
 * @method void makeUnique($attribute, $postfix = '') adds number to the end of attribute login till it is unique.
 * @method void makeUniqueFile($attribute) adds number to the end of attribute login till it is unique.
 */
class User extends CActiveRecord
{
	const STATUS_NOACTIVE=0;
	const STATUS_ACTIVE=1;
	const STATUS_BANNED=-1;

    public $newPassword = '';

	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return Yii::app()->getModule('user')->tableUsers;
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.CConsoleApplication
		return ((get_class(Yii::app())=='CConsoleApplication' || (get_class(Yii::app())!='CConsoleApplication' && Yii::app()->getModule('user')->isAdmin()))?array(
			array('username', 'length', 'max'=>20, 'min' => 3,'message' => UserModule::t("Incorrect username (length between 3 and 20 characters).")),
			array('password', 'length', 'max'=>128, 'min' => 4,'message' => "Minimal password length 4 characters."),
			array('email', 'email'),
            array('newPassword', 'safe'),
			array('username', 'unique', 'message' => UserModule::t("This user's name already exists.")),
			array('email', 'unique', 'message' => UserModule::t("This user's email address already exists.")),
			array('username', 'match', 'pattern' => '/^[A-Za-z0-9_ .]+$/u','message' => UserModule::t("Incorrect symbols (A-z0-9_ .).")),
			array('status', 'in', 'range'=>array(self::STATUS_NOACTIVE,self::STATUS_ACTIVE,self::STATUS_BANNED)),
			array('role', 'in', 'range'=>array(0,1,2)),
            array('create_at', 'default', 'value' => date('Y-m-d H:i:s'), 'setOnEmpty' => true, 'on' => 'insert'),
            array('lastvisit_at', 'default', 'value' => '0000-00-00 00:00:00', 'setOnEmpty' => true, 'on' => 'insert'),
			array('username, email, role, status', 'required'),
			array('role, status', 'numerical', 'integerOnly'=>true),
			array('id, username, password, email, activkey, create_at, lastvisit_at, role, status, ontraportId', 'safe', 'on'=>'search'),
		):((Yii::app()->user->id==$this->id)?array(
			array('username, email', 'required'),
			array('username', 'length', 'max'=>20, 'min' => 3,'message' => UserModule::t("Incorrect username (length between 3 and 20 characters).")),
			array('email', 'email'),
			array('username', 'unique', 'message' => UserModule::t("This user's name already exists.")),
			array('username', 'match', 'pattern' => '/^[A-Za-z0-9_ .]+$/u','message' => UserModule::t("Incorrect symbols (A-z0-9_ .).")),
			array('email', 'unique', 'message' => UserModule::t("This user's email address already exists.")),

		):array()));
	}

	public function behaviors()
	{
        return array(
            'makeUniqueBehavior' => array(
                'class' => 'ext.behaviors.MakeUniqueBehavior',
            ),
        );
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
        return Yii::app()->getModule('user')->relations + array(
            'profile' => array(self::HAS_ONE, 'Profile', 'user_id'),
            'userCourse' => array(self::HAS_MANY, 'UserCourse', 'user_id', 'index' => 'course_id'),
            'subscription' => array(self::BELONGS_TO, 'UserCourse', 'id'),
            'badges' => array(self::MANY_MANY, 'Badges', 'user_badge(user_id, badge_id)'),
            'roles'=>array(self::HAS_ONE,'User','id'),
            'userBadges' => array(self::HAS_MANY, 'UserBadge', 'user_id'),
        );
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => UserModule::t("Id"),
			'username'=>UserModule::t("Username"),
			'password'=>UserModule::t("Password"),
			'verifyPassword'=>UserModule::t("Retype Password"),
			'email'=>UserModule::t("E-mail"),
			'verifyCode'=>UserModule::t("Verification Code"),
			'activkey' => UserModule::t("Activation key"),
			'createtime' => UserModule::t("Registration date"),
			'create_at' => UserModule::t("Registration date"),
			
			'lastvisit_at' => UserModule::t("Last visit"),
			'role' => UserModule::t("Role"),
			'status' => UserModule::t("Status"),
			'newPassword' => UserModule::t("Set Password"),
                        'ontraportId' => 'Ontraport Id'
		);
	}
	
	public function scopes()
    {
        return array(
            'active'=>array(
                'condition'=>'status='.self::STATUS_ACTIVE,
            ),
            'notactive'=>array(
                'condition'=>'status='.self::STATUS_NOACTIVE,
            ),
            'banned'=>array(
                'condition'=>'status='.self::STATUS_BANNED,
            ),
            'role'=>array(
                'condition'=>'role=1',
            ),
            'notsafe'=>array(
            	'select' => 'id, username, password, email, activkey, create_at, lastvisit_at, role, status',
            ),
        );
    }
	
	public function defaultScope()
    {
        return CMap::mergeArray(Yii::app()->getModule('user')->defaultScope,array(
            'alias'=>'user',
            //'select' => 'user.id, user.username, user.email, user.create_at, user.lastvisit_at, user.role, user.status',
        ));
    }
	
	public static function itemAlias($type,$code=NULL) {
		$_items = array(
			'UserStatus' => array(
				self::STATUS_NOACTIVE => UserModule::t('Not active'),
				self::STATUS_ACTIVE => UserModule::t('Active'),
				self::STATUS_BANNED => UserModule::t('Banned'),
			),
			'AdminStatus' => array(
				'0' => UserModule::t('User'),
				'1' => UserModule::t('Admin'),
                '2' => UserModule::t('EconomicEventsEditor'),
			),
		);
		if (isset($code))
			return isset($_items[$type][$code]) ? $_items[$type][$code] : false;
		else
			return isset($_items[$type]) ? $_items[$type] : false;
	}
	
    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria=new CDbCriteria;

        $criteria->with = array('subscription');
        
        $criteria->compare('user.id',$this->id);
        $criteria->compare('username',$this->username,true);
        $criteria->compare('password',$this->password);
        $criteria->compare('email',$this->email,true);
        $criteria->compare('activkey',$this->activkey);
        $criteria->compare('create_at',$this->create_at);
        $criteria->compare('lastvisit_at',$this->lastvisit_at);
        $criteria->compare('role',$this->role);
        $criteria->compare('status',$this->status);
        $criteria->compare('ontraportId',$this->ontraportId);
        
        return new CActiveDataProvider(get_class($this), array(
            'criteria'=>$criteria,
        	'pagination'=>array(
				'pageSize'=>Yii::app()->getModule('user')->user_page_size,
			),
        ));
    }

    public function getCreatetime() {
        return strtotime($this->create_at);
    }

    public function setCreatetime($value) {
        $this->create_at=date('Y-m-d H:i:s',$value);
    }

    public function getLastvisit() {
        return strtotime($this->lastvisit_at);
    }

    public function setLastvisit($value) {
        $this->lastvisit_at=date('Y-m-d H:i:s',$value);
    }

    public function afterSave() {
        if (get_class(Yii::app())=='CWebApplication'&&Profile::$regMode==false) {
            Yii::app()->user->updateSession();
        }
        return parent::afterSave();
    }

    /**
     * @param $courseId course id
     * @return bool if user subscribed on course
     */
    public function isSubscribedOnCourse($courseId)
    {
        Yii::trace('Checking user #' . $this->id . ' is subscribed on course #' . $courseId, 'application.assertions');
        
        if (Yii::app()->user->isAdmin())
            return true;

        return
            isset($this->userCourse[$courseId]);
    }

    /**
     * Returns amount of unread messages for current authenticated user
     * if $fromUserId > 0 get messages only from certain user
     *
     * @param int $fromUserId user id
     * @return string
     */
    public function getAmountOfUnreadMessages($fromUserId = 0)
    {
        $arr = array(
            'user_to' => Yii::app()->user->id,
            'is_read' => 0,
        );

        if ($fromUserId > 0)
            $arr['user_from'] = $fromUserId;

        $count = Messages::model()->countByAttributes($arr);

        if ($count == 0)
            return '';

        return $count;
    }


    /**
     * Checks if user is subscribed on course and this course has calendar opened by admin
     * @param null $courseId
     * @return bool
     */
    public function getHasAccessToCalendarOfCourse($courseId = null)
    {
        if ($courseId != null)
            $courseIds[] = $courseId;
        else
            $courseIds = Yii::app()->db->createCommand()
                        ->select('id')
                        ->from( Courses::model()->tableName() )

courses.2ndskiesforex.com/protected/modules/user/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return CMap::mergeArray(parent::filters(),array(
			'accessControl', // perform access control for CRUD operations
		));
	}
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'getUsers', 'subscriptions'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}	

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$model = $this->loadModel();
		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User', array(
			'criteria'=>array(
		        'condition'=>'status>'.User::STATUS_BANNED,
		    ),
				
			'pagination'=>array(
				'pageSize'=>Yii::app()->controller->module->user_page_size,
			),
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=User::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the primary key value. Defaults to null, meaning using the 'id' GET variable
	 */
	public function loadUser($id=null)
	{
		if($this->_model===null)
		{
			if($id!==null || isset($_GET['id']))
				$this->_model=User::model()->findbyPk($id!==null ? $id : $_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

    public function actionGetUsers()
    {
        $query  = Yii::app()->request->getParam('query');

        $criteria = new CDbCriteria;
        $criteria->addSearchCondition('username', $query);
        $criteria->limit = 20;

        $items = User::model()->findAll($criteria);

        $res = array();
        foreach ($items as $item) {
            $res[] = array(
                'string' => implode('|', array(
                    $item->id,
                    $item->username,
                ))
            );
        }

        Yii::app()->end(CJSON::encode($res));
    }



}

courses.2ndskiesforex.com/protected/modules/user/views/user/afterActivation.php
<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login"); ?>

<h1><?php echo $title; ?></h1>

<div class="form">
    <?php echo $content; ?>

</div><!-- yiiForm -->
<script>
    setTimeout(function () {
        window.location.href = "/user/login";
    }, 4000);
</script>

courses.2ndskiesforex.com/protected/modules/user/views/user/index.php
<?php
$this->breadcrumbs=array(
	UserModule::t("Users"),
);
if(UserModule::isAdmin()) {
	$this->layout='//layouts/column2';
	$this->menu=array(
	    array('label'=>UserModule::t('Manage Users'), 'url'=>array('/user/admin/manage')),
	    array('label'=>UserModule::t('Manage Profile Field'), 'url'=>array('profileField/admin')),
	);
}
?>

<h1><?php echo UserModule::t("List User"); ?></h1>

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'dataProvider'=>$dataProvider,
	'columns'=>array(
		array(
			'name' => 'username',
			'type'=>'raw',
			'value' => 'CHtml::link(CHtml::encode($data->username),array("user/view","id"=>$data->id))',
		),
		'create_at',
		'lastvisit_at',
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
        ),
	),
)); ?>

courses.2ndskiesforex.com/protected/modules/user/views/user/login.php
<?php
$this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login");
// Add custom stylesheet - login.css
Yii::app()->clientScript->registerCssFile('/2ndskiesdev-project/live/courses.2ndskiesforex.com/css/login.css');
?>

<div class="login-form-wrap">

    <img src='http://2ndskiesforex.com/wp-content/themes/2ndSkies/library/images/login-logo.png' class='login-logo' />
    
    <?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id'=>'login-form',
        'enableClientValidation'=>true,
        'htmlOptions'=>array('class'=>'form-login'),
        'clientOptions'=>array(
            'validateOnSubmit'=>true,
        ),
    )); /* @var $form TbActiveForm */ ?>
    
        <h1><?php echo UserModule::t("Login"); ?></h1>
    
        <?php if(Yii::app()->user->hasFlash('loginMessage') || Yii::app()->user->hasFlash('recoveryMessage')): ?>
        
            <div class="success">
                <?php echo Yii::app()->user->getFlash('loginMessage'); ?>
                <?php echo Yii::app()->user->getFlash('recoveryMessage'); ?>
            </div>
        
        <?php endif; ?>
    
        <?php echo $form->errorSummary($model, 'Following errors occurred'); ?>
        
        <div class="controls-row">
            <?php echo $form->textField($model,'username', array('class'=>'input-block-level', 'placeholder'=>'Username or email')); ?>
            <?php echo $form->error($model,'username'); ?>
        </div>
        
        <div class="controls-row">
            <?php echo $form->passwordField($model,'password', array('class'=>'input-block-level', 'placeholder'=>'Password')); ?>
            <?php echo $form->error($model,'password'); ?>
        </div>
        
        <div class="clearfix button-wrap">
        
            <?php echo $form->checkBoxRow($model,'rememberMe'); ?>
            
            <?php 
                $this->widget('bootstrap.widgets.TbButton', array(
                    'buttonType'=>'submit',
                    'type'=>'primary',
                    'size'=>'large',
                    'label'=>'Login',
                    'htmlOptions'=>array('class'=>'pull-right'),
                )); 
            ?>
            
        </div><!-- .button-wrap -->
        
        <ul class="action-links">
            <?php echo '<li>'.CHtml::link(UserModule::t("Register"),Yii::app()->createUrl('/courses/list')).'</li>'; ?>
            <?php echo '<li>'.CHtml::link(UserModule::t("Lost Password?"),Yii::app()->getModule('user')->recoveryUrl).'</li>'; ?>
        </ul>
            
        <div class="clearfix"></div>
    
    <?php $this->endWidget(); ?>

</div><!-- .login-form-wrap -->

courses.2ndskiesforex.com/protected/modules/user/views/user/message.php
<?php $this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Login"); ?>

<h1><?php echo $title; ?></h1>

<div class="form">
<?php echo $content; ?>

</div><!-- yiiForm -->

courses.2ndskiesforex.com/protected/modules/user/views/user/registration.php
<?php

$this->pageTitle=Yii::app()->name . ' - '.UserModule::t("Registration");


Yii::app()->clientScript->registerCssFile('/css/form.css');
?>

<div class="buy-box">
	<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
		'id'=>'registration-form',
		'type'=>'horizontal',
		'enableAjaxValidation'=>true,
		'clientOptions'=>array(
			'validateOnSubmit'=>true,
            'afterValidate' => 'js:function(data, errors){if(errors > 0) $("#error-msg").toggleClass("hidden", !errors); return true;}',
		),
		'htmlOptions' => array('enctype'=>'multipart/form-data'),
	));

//	$form=$this->beginWidget('CActiveForm', array(
//		'id'=>'registration-form',
//		'enableAjaxValidation'=>true,
//		//'enableClientValidation'=>true,
//		'clientOptions'=>array('validateOnSubmit'=>true,'afterValidateAttribute'=>new CJavaScriptExpression("function(form, attribute, data, hasError){
//                var id='RegistrationForm_verifyPassword';
//                var eid='RegistrationForm_verifyPassword_em_';
//
//                if(data[id] === undefined )
//                {
//        				$('#RegistrationForm_verifyPassword_em_').css('display','none');
//        		  		$('#success-image.flash-success').css('display','block');
//                        $('#'+id).parent().children('label.required').css('color','green');
//
//                }
//
//                else
//                {
//                        $('#success-image.flash-success').css('display','none');
//                        $('#'+id).parent().children('.errorMessage').css('color','red');
//                        $('#'+id).css('background','').addClass('error');
//                }
//                }")),
//
//	));

	?>
	<ul class="steps-list">
		<li class="active"><a href="#"><i class="counter"><b>1</b></i><span class="text">Registration</span></a></li>
		<li><a href="#"><i class="counter"><b>2</b></i><span class="text">Payment info</span></a></li>
		<li><a href="#"><i class="counter"><b>3</b></i><span class="text">Finish</span></a></li>
	</ul>
	<div class="buy-box-holder">

		<?php if(Yii::app()->user->hasFlash('registration')): ?>
			<div class="alert alert-success">
				<?php echo Yii::app()->user->hasFlash('registration'); ?>
			</div>
		<?php else: ?>
			<p class="note"><?php echo UserModule::t('Fields with <span class="required">*</span> are required.'); ?></p>

			<div id="error-msg" class="alert alert-block alert-error hidden">Please fix the following input errors.</div>

			<span id="are-you-real" class="hidden"></span>
			<div class="half-box-holder">
				<div class="half-box">
					<?php
					$profileFields=Profile::getFields();
					if ($profileFields) {
						foreach($profileFields as $field) {
							$field['title']=ucfirst(strtolower($field['title']));
							?>
							<?php
							echo '<div class="control-group"><div class="heading-box">';
							echo $form->labelEx($profile,$field->varname, array('class'=>'block-label filed_name'));

							if ($widgetEdit = $field->widgetEdit($profile)) {
								?>	<div class= "help-inline error">	<?php	echo $form->error($profile,$field->varname);?></div><?php
								echo '</div>';
								echo $widgetEdit;
							} elseif ($field->range) {
								?>	<div class= "help-inline error">	<?php	echo $form->error($profile,$field->varname);?></div><?php
								echo '</div>';
								$disabledValues = array('----------'=> Array ( 'disabled' => 'disabled' ));
								echo $form->dropDownList($profile,$field->varname,Profile::range($field->range),array(
									'options' => $disabledValues,
									'class' => 'chosen chosen-container chosen-container-single	',
									'style' => 'width: 321px;font-size: 15.5px !important;padding: 3px 1px 1px 1px; ',
								));
							} elseif ($field->field_type=="TEXT") {
								?>	<div class= "help-inline error">	<?php echo $form->error($profile,$field->varname);?></div><?php
								echo '</div>';
								echo $form->textArea($profile,$field->varname,array('rows'=>6, 'cols'=>50));
							} else {
								?>	<div class= "help-inline error">	<?php echo $form->error($profile,$field->varname);?></div><?php
								echo '</div>';
								echo $form->textField($profile,$field->varname,array('size'=>60,'maxlength'=>(($field->field_size)?$field->field_size:255)));
							}
							echo '</div>';
							?>

						<?php
						}
					}
					?>
					<div class="control-group">
						<div class="heading-box">
							<div class= "help-inline error"><?php echo $form->error($model,'email'); ?></div>
							<?php echo $form->labelEx($model,'email',array('class'=> 'block-label')); ?>
						</div>
						<?php echo $form->textField($model,'email'); ?>
					</div>
				</div>
				<div class="half-box">
					<div class="control-group">
						<div class="heading-box">
							<div id="success-image-username" class="flash-success" style="display:none;">
								<img class="" src="/images/check-mark.png" alt="" height="16px" width="16px"  style="float: right;"/>
							</div>
							<div class= "help-inline error"><?php echo $form->error($model,'username'); ?></div>
							<?php echo $form->labelEx($model,'username',array('class'=> 'block-label')); ?>
						</div>
						<?php echo $form->textField($model,'username'); ?>
					</div>
					<div class="control-group">
						<div class="heading-box">
							<div id="success-image-pass" class="flash-success" style="display:none;">
								<img class="" src="/images/check-mark.png" alt="" height="16px" width="16px"  style="float: right;"/>
							</div>
							<div class= "help-inline error"><?php echo $form->error($model,'password'); ?></div>
							<span class="help-text"><?php echo "Minimum password length 4 characters"; ?></span>
							<?php echo $form->labelEx($model,'password',array('class'=> 'block-label')); ?>
						</div>
						<?php echo $form->passwordField($model,'password'); ?>
					</div>
					<div class="control-group">
						<div class="heading-box">
							<div id="success-image" class="flash-success" style="display:none;">
								<img class="" src="/images/check-mark.png" alt="" height="16px" width="16px"  style="float: right;"/>
								<?php // echo $form->error($ghost,'verifyPassword',array('style'=>"color:darkblue;",'class'=>'flash-success'));?>
							</div>
							<div class= "help-inline error"><?php echo $form->error($model,'verifyPassword'); ?></div>
							<?php echo $form->labelEx($model,'verifyPassword',array('label'=>'Retype password','class'=> 'block-label')); ?>
						</div>
						<?php echo $form->passwordField($model,'verifyPassword'); ?>
					</div>
				</div>

			</div>
			<div class="mb20 text-right">
				<?php $this->widget('bootstrap.widgets.TbButton', array(
					'buttonType'=>'submit',
					'type'=>'primary',
					'label'=>'Next',
					'htmlOptions'=>array('class'=>'btn-gold'),
				)); ?>
			</div>
			<div class="buy-box-bottom">
				<img src="/images/comodo.png" alt=""/>
				<img class="payment-img" src="/images/payment.png" alt=""/>
			</div>

		<?php endif; ?>
		<?php $this->endWidget(); ?>
	</div>
</div>
<ul class="list-testimonials">
	<li class="testimonial">
		<i class="icon-quote"></i>
		<p class="testimonial--quote">I made 3% in 3 days since obtaining the courses, they are excellent...I appreciate what you have done for me, even in this little time, I feel like with hard work, I have a light at the end of the tunnel :)</p>
		<h3 class="testimonial--title">Ken T</h3>
	</li>
</ul>

<script>
	$(document).ready(function(){
		$('#are-you-real').html('<input class="hidden" value=1 name="areYouReal">');
	})

	$("#RegistrationForm_password").keyup(function(){
		if($("#RegistrationForm_password").val().length >= 4)
		{
			$("#RegistrationForm_password_em_").css("display","none");
			$(".help-text").css("display","none");
			$("#success-image-pass").css("display","block");
		}
		else{
			$("#RegistrationForm_password_em_").css("display","none");
		}
	});

	/*  $("#RegistrationForm_username").keyup(function(){
	 if($("#RegistrationForm_username").val().length >= 4)
	 {
	 $("#RegistrationForm_username_em_").css("display","none");
	 $("#success-image-username").css("display","block");
	 }
	 else{
	 $("#RegistrationForm_username_em_").css("display","none");
	 }
	 }); */

</script>

courses.2ndskiesforex.com/protected/modules/user/views/user/view.php
<?php
$this->breadcrumbs=array(
	UserModule::t('Users')=>array('index'),
	$model->username,
);
$this->layout='//layouts/column2';
$this->menu=array(
    array('label'=>UserModule::t('List User'), 'url'=>array('manage')),
);
?>
<h1 class="content-title"><?php echo UserModule::t('View User').' "'.$model->username.'"'; ?></h1>
<?php 

// For all users
	$attributes = array(
			'username',
	);
	
	$profileFields=ProfileField::model()->forAll()->sort()->findAll();
	if ($profileFields) {
		foreach($profileFields as $field) {
			array_push($attributes,array(
					'label' => UserModule::t($field->title),
					'name' => $field->varname,
					'value' => (($field->widgetView($model->profile))?$field->widgetView($model->profile):(($field->range)?Profile::range($field->range,$model->profile->getAttribute($field->varname)):$model->profile->getAttribute($field->varname))),

				));
		}
	}
	array_push($attributes,
		'create_at',
		array(
			'name' => 'lastvisit_at',
			'value' => (($model->lastvisit_at!='0000-00-00 00:00:00')?$model->lastvisit_at:UserModule::t('Not visited')),
		)
	);
			
	$this->widget('bootstrap.widgets.TbDetailView', array(
		'data'=>$model,
		'attributes'=>$attributes,
	));

?>