courses.2ndskiesforex.com/protected/controllers/TopicController.php
<?php

class TopicController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('view','comment','create','upload','imageUpload','reply','editComment','subscribe','unsubscribe','subscriptionNotify'),
				'users'=>array('@'),
			),
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('deleteComment', 'deleteTopic', 'replaceTopic'),
                'users'=>Yii::app()->getModule('user')->getAdmins(),
            ),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */

	public function actionCreate($section_id = null)
	{
        $section = Sections::model()->findByPk($section_id);
        $this->setActiveSection($section);

        $userId = Yii::app()->user->id;
        $date = new CDbExpression('NOW()');

        $modelTopic=new Topic;
        $modelTopic->section_id = $section_id;
        $modelTopic->user_id = $userId;
        $modelTopic->date_changed = $modelTopic->date_created = $date;

        $modelComment = new Comment;
        $modelComment->is_first = 1;
        $modelComment->user_id = $userId;
        $modelComment->date_changed = $modelComment->date_created = $date;

		if(isset($_POST['Topic']))
        {
            $modelTopic->attributes=$_POST['Topic'];

            $modelTopic->save();

            if(isset($_POST['Comment']))
            {
                $modelComment->text = $_POST['Comment'];

                $modelComment->topic_id = $modelTopic->id;
                if($modelComment->save()){
                    $modelTopic->first_comment_id = $modelComment->id;
                    $modelTopic->save(false,array('first_comment_id'));

                    if($modelTopic->status != 1)
                        Subscriptions::model()->newSubscription($modelTopic->id);

                    $this->redirect(array('view','id'=>$modelTopic->id));
                }
            }
        }

		$this->render('create',array(
			'model'=>$modelTopic
		));
	}

    /**
     * Creates a new comment for a topic.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param integer $topic_id
     */
    public function actionComment($topic_id)
    {
        $topic = $this->loadModel($topic_id);

        $this->assertCourseAccessible($topic->section->course_id);

        $modelComment = new Comment;
        $modelComment->topic_id = $topic_id;
        $modelComment->is_first = 0;
        $modelComment->user_id = Yii::app()->user->id;
        $modelComment->date_changed = $modelComment->date_created = new CDbExpression('NOW()');

        $topic->date_changed = new CDbExpression('NOW()');
        if(isset($_POST['Comment']))
        {
            $text = $_POST['Comment']['text'];
            //$text = preg_replace('/(iframe\s+[^>]*src=")(http:|https:)([^"]*"[^>])*/','$1$3',$text);
            //$text = preg_replace('/(src=")(http:|https:)([^"]*"*)/','$1$3',$text);

            $modelComment->attributes = $_POST['Comment'];
            $modelComment->text = $text;
           $topic->save();
           if($modelComment->save())
           {
               $this->sendNotification($topic->subject, $modelComment->user->username, $topic_id, $topic->user_id);
               $this->redirect($modelComment->getCommentUrl($modelComment->id));
           }
        }
        $this->redirect(Yii::app()->createUrl('topic/view',array('id'=>$topic_id)));

    }

    /**
     * Edit a comment for a topic.
     * If editing is successful, the browser will be redirected to the 'view' page.
     * @param integer $id - comment id
     * @throw CHttpException 404 if user does not have access to a course
     */
    public function actionEditComment($id)
    {
        $comment = Comment::model()->findByPk($id);
        $topic = $this->loadModel($comment->topic_id);

        $section = Sections::model()->findByPk($topic->section_id);
        if (! Yii::app()->user->model()->isSubscribedOnCourse($section->course_id))
            throw new CHttpException(404,'You don\'t have access on this course');

        if(isset($_POST['Comment']))
        {
            $text = $_POST['Comment']['text'];
           // $text = preg_replace('/(iframe\s+[^>]*src=")(http:|https:)([^"]*"[^>])*/','$1$3',$text);
           // $text = preg_replace('/(src=")(http:|https:)([^"]*"*)/','$1$3',$text);

            $comment->attributes = $_POST['Comment'];
            $comment->text = $text;
            if($comment->save())
                $this->redirect($comment->getCommentUrl($comment->id));
        }

        $this->redirect(Yii::app()->createUrl('topic/view',array('id'=>$comment->topic_id,'#'=>$comment->id)));

    }

    /**
     * Delete a comment for a topic.
     * @param integer $commentId
     */
    public function actionDeleteComment()
    {
        $commentId = Yii::app()->request->getPost('commentId',null);
        Comment::model()->findByPk($commentId)->delete();
    }

    /**
     * Delete a topic.
     * If deleting is successful, the browser will be redirected to the 'view' page of next topic.
     * @param integer topicId
     */
    public function actionDeleteTopic()
    {
        $topicId = Yii::app()->request->getPost('topicId',null);

        $topic = Topic::model()->findByPk($topicId);
        if ($topic->delete())
            Comment::model()->deleteAllByAttributes(array('topic_id' => $topic->id));

        $nextTopicId = Topic::model()->getNextTopicId($topic->id, $topic->section_id);
        if ($nextTopicId) {
            echo Yii::app()->createAbsoluteUrl('/topic/view', array('id' => $nextTopicId));
        } else {
            $courseId = Yii::app()->session['courseId'];
            echo Yii::app()->createAbsoluteUrl('/courses/sectionlist', array('courseId' => $courseId, 'sectionId' => $topic->section_id, 'isMenu' => true));
        }
    }

    /**
     * Move a topic to another section.
     *
     * @params integer $sectionId, $topicId
     * @return string
     */
    public function actionReplaceTopic()
    {
        $sectionId = Yii::app()->request->getPost('sectionId',null);
        $topicId = Yii::app()->request->getPost('topicId',null);

        if($sectionId && $topicId)
        {
            $topic = Topic::model()->findByPk($topicId);
            $topic->section_id = $sectionId;
            if($topic->save())
                echo '<div class="alert alert-block alert-success" id="user-message">You have successfully moved topic!</div>';
            else
                echo '<div class="alert alert-block alert-error" id="user-message">The topic was not moved. Please, try again.</div>';

        }

        Yii::app()->cache->flush();
        Yii::app()->end();
    }

    /**
     * View a topic.
     *
     * @params integer $id - topic id, $isSingleVideoLayout
     */
	public function actionView($id, $isSingleVideoLayout = null)
    {
        $topic = $this->loadModel($id);

        $this->setActiveSection($topic->section);
        
        $model = new Comment;
        $model->topic_id = $id;

        $this->saveLastCommentToSubscriptions($id, Yii::app()->user->id);

        $this->render('view',array(
            'model'=>$model,
            'dataProvider' => $model->searchComments($isSingleVideoLayout),
            'topic'=>$topic,
        ));
    }

    /**
     * Subscribe to a topic.
     *
     * @params integer $topicId
     * @return string
     */
    public function actionSubscribe()
    {
        $topicId = Yii::app()->request->getPost('id',null);
        $userId = Yii::app()->user->id;
        $courseId = Yii::app()->session['courseId'];

        $lastCommentId = Topic::model()->findByPk($topicId)->getAttribute('last_comment_id');

        $userSubscriptions = Subscriptions::model()->findByAttributes(array('user_id'=>$userId, 'course_id'=>$courseId));

        if(!empty($userSubscriptions))
            $userSubscriptions->topic_id_arr .= ','.$topicId.'=>'.$lastCommentId.',';
        else
        {
            $userSubscriptions = new Subscriptions();
            $userSubscriptions->user_id = $userId;
            $userSubscriptions->course_id = $courseId;
            $userSubscriptions->topic_id_arr = ','.$topicId.'=>'.$lastCommentId.',';
        }

        if($userSubscriptions->save())
            echo '<div class="alert alert-block alert-success" id="user-message">You have successfully subscribed to the topic!</div>';
        else
            echo '<div class="alert alert-block alert-error" id="user-message">You subscription was not saved. Please, try again.</div>';

        Yii::app()->end();
    }

    /**
     * Unsubscribe to a topic.
     *
     * @params integer $topicId
     * @return string
     */
    public function actionUnsubscribe()
    {
        $topicId = Yii::app()->request->getPost('id',null);

        $lastCommentId = Topic::model()->findByPk($topicId)->getAttribute('last_comment_id');
        $userSubscriptions = Subscriptions::model()->findByAttributes(array('user_id'=>Yii::app()->user->id, 'course_id'=>Yii::app()->session['courseId']));

        $subscriptions = str_replace(array(','.$topicId.'=>'.$lastCommentId.',',','.$topicId.','), '',$userSubscriptions->topic_id_arr);

courses.2ndskiesforex.com/protected/views/video_lessons/_topic.php
<?php
//$this->layout = 'sectionlist';
?>

<div class="well well-blue">
    <div>
        <div class="row-fluid" id="c<?= $topic->id ?>">
            <div class="span8 pull-center">
                <div class="content">
                    <h3><?=$topic->subject?></h3>
                        <?php
                        $text = $topic->comments->text;
                        $text = $topic->comments->hideSrcIframe($text, $topic->id);
                        $text = preg_replace('/(iframe\s+[^>]*)(src=")(http:|https:)([^"]*"[^>]*)/','$1$2$4',$text);
                        //$text = preg_replace('/(src=")(http:|https:)([^"]*"*)/','$1$3',$text);
                        echo $text;?>
                </div>
            </div>
        </div>
    </div>
    <?php
    if ($topic->discussion == 1) {
        echo '<h5> Lessons Discussions</h5>';

        $this->widget('bootstrap.widgets.TbGridView', array(
            'template' => "{items}{pager}",
            'dataProvider' => $topic->search(),
            'columns' => array(
                array(
                    'name' => 'subject',
                    'value' => '$data->getTheme(1)',
                    'type' => 'html',
                    'htmlOptions' => array(
                        'class' => 'text-left bold'
                    ),
                ),
                array(
                    'name' => 'replies',
                    'value' => '$data->replies',
                    'htmlOptions' => array(
                        'class' => 'text-left bold'
                    ),
                ),
                array(
                    'name' => 'lastPost',
                    'value' => '$data->lastPost',
                    'type' => 'html',
                    'htmlOptions' => array(
                        'class' => 'text-left bold'
                    ),
                ),


            ),
        ));
    }
    ?>

</div>

<script type="text/javascript">
function myFunction() {
    var startTime = "<?php echo date("Y-m-d h:i a") ?>";	
		$.ajax({
				url : "http://courses.2nd-skies-forex.com/courses/usertrack/",
				type : "POST",
				data : {
					action : "ignore_user_track",
					startTime : startTime,
					logInsertID : "<?php echo $logInsertID; ?>"
				},
				success : function(response){
				}
			});
}
</script>
<script>
function IntervalFunction() {
    setInterval(function(){ myFunction() }, 10000);
}
IntervalFunction();
</script>

courses.2ndskiesforex.com/protected/views/video_lessons/view.php
<?php

/* @var $currentSection Sections */

// there is a selected section
$sectionShown = !empty($currentSection);

echo '<div class="well well-blue">';

if (!empty($sections)) {
    // Section block
    $dataProvider=new CArrayDataProvider($sections);
    $this->widget('bootstrap.widgets.TbListView', array(
        'htmlOptions'=>array('class'=>'table-blue'),
        'dataProvider'=>$dataProvider,
        'viewData' => array('courseId' => $course->id),
        'itemView'=>'//courses/sections/_list_item',
        'summaryText'=>'Sections',
        'summaryCssClass'=>'list-summary',
        'itemsTagName' => 'table',
        'itemsCssClass'=> 'items table',
    ));
}
// Topics block

if (isset($currentSection)) {

    $announsementsCount = Topic::model()->count("status = 1 AND section_id = $currentSection->id");

    if ($announsementsCount) {
        $topics = Topic::model()->findAllByAttributes(array('status'=>1,'section_id'=>$currentSection->id),array('order'=>'t.order ASC'));

        if (!Yii::app()->user->isAdmin()) {
            $userCourse = UserCourse::model()->findByAttributes(array('user_id' => Yii::app()->user->id, 'course_id' => $course->id));
        }

    foreach($topics as $topic) {?>
        <?php
        if (Yii::app()->user->isAdmin() || time() > strtotime("+$topic->time_release day", strtotime($userCourse->created))) {
            $video = Comment::model()->findByAttributes(array('topic_id'=>$topic->id, 'is_first'=>1));?>
            <br>
            <div>
                <div class="row-fluid" id="c<?= $video->id ?>">
                    <div class="span8 pull-center">
                        <div class="content">
                            <h3><?=$topic->subject?></h3>
                            <?php
                            $text = $video->text;
                            $text = $video->hideSrcIframe($text, $topic->id);
                            $text = preg_replace('/(iframe\s+[^>]*)(src=")(http:|https:)([^"]*"[^>]*)/','$1$2$4',$text);
                            //$text = preg_replace('/(src=")(http:|https:)([^"]*"*)/','$1$3',$text);
                            echo $text;

//                            if (Yii::app()->session['courseId'] != 3 && Yii::app()->session['courseId'] != 4)
//                                echo '<center><a class="btn btn-large btn-info" href="/courses/quiz?sectionId='.$currentSection->parent_id.'"><i class="icon-hand-up"></i> Quiz</a></center>';
                            ?>

                        </div>
                    </div>
                </div>
            </div>
        <?php }?>

    <?php }
        echo '<h5> Lessons Discussions</h5>';

        $this->widget('bootstrap.widgets.TbGridView', array(
            'template' => "{items}{pager}",
            'dataProvider' => $currentSection->getTopicsProvider(array(
                'select' => 'id, subject, date_created',
                'condition' => 't.status = 1 AND t.discussion = 1',
                'with' => array(
                    'user' => array('select' => 'id, username'),
                    'replies',
                    'lastComment' => array(
                        'select' => 'date_created',
                        'with' => array(
                            'user' => array(
                                'select' => 'username',
                                'alias' => 'lcu',
                            ),
                        ),
                    ),
                    'firstComment' => array(
                        'select' => 'text, stripped_tag_text',
                    ),
                ),
                'order'=>'t.order ASC'
            )),
            'columns' => array(
                array(
                    'name' => 'subject',
                    'value' => '$data->getTheme(1)',
                    'type' => 'html',
                    'sortable' => false,
                    'htmlOptions' => array(
                        'class' => 'text-left bold'
                    ),
                ),
                array(
                    'name' => 'replies',
                    'value' => '$data->replies',
                    'htmlOptions' => array(
                        'class' => 'text-left bold'
                    ),
                ),
                array(
                    'name' => 'lastPost',
                    'value' => '$data->lastPost',
                    'type' => 'html',
                    'htmlOptions' => array(
                        'class' => 'text-left bold'
                    ),
                ),
            ),
        ));
    }
}
if ($sectionShown) {

    echo '<h5> General Discussions</h5>';

    $this->widget('bootstrap.widgets.TbGridView',array(
        'id'=>'topic-grid',
        'template'=>"{items}{pager}",
        'dataProvider'=> $currentSection->getTopicsProvider(array(
            'select' => 'id, subject, date_created',
            'condition' => 't.status != 1 AND t.discussion = 1',
            'with' => array(
                'user' => array('select' => 'id, username'),
                'replies',
                'lastComment' => array(
                    'select' => 'date_created',
                    'with' => array(
                        'user' => array(
                            'select' => 'username',
                            'alias' => 'lcu',
                        ),
                    ),
                ),
            ),
        )),
        'columns'=>array(
            array(
                'name' => 'subject',
                'value' => '$data->theme',
                'type' => 'html',
                'sortable' => false,
                'htmlOptions' => array(
                    'class' => 'text-left bold'
                ),
            ),
            array(
                'name' => 'replies',
                'value' => '$data->replies',
                'htmlOptions' => array(
                    'width' => '70px',
                    'class' => 'text-left bold'
                ),
            ),
            array(
                'name' => 'lastPost',
                'value' => '$data->lastPost',
                'type' => 'html',
                'htmlOptions' => array(
                    'width' => '200px',
                    'class' => 'text-left bold'
                ),
            ),
            array(
                'name' => 'date_created',
                'htmlOptions' => array('width' => '150px')
            )
        ),
    ));

    $this->widget('bootstrap.widgets.TbButton', array(
        'type'=>'primary',
        'label'=>'New topic',
        'url'=>Yii::app()->createUrl('topic/create', array('section_id' => $currentSection->id))
    ));
}

echo '</div>';
echo '
<script type="text/javascript">
function myFunction() {
    var startTime = "'.date("Y-m-d h:i a").'";	
		$.ajax({
				url : "http://courses.2nd-skies-forex.com/courses/usertrack/",
				type : "POST",
				data : {
					action : "ignore_user_track",
					startTime : startTime,
					logInsertID : "'.$logInsertID.'"
				},
				success : function(response){
				}
			});
}
</script>
<script>
function IntervalFunction() {
    setInterval(function(){ myFunction() }, 10000);
}
IntervalFunction();
</script>';